from shared.model_types import ModelConfig, ProviderConfig


QWEN_PROVIDER = ProviderConfig(
    id="qwen",
    name="通义千问",
    display_name="通义千问 (Qwen)",
    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
    auth_header="Authorization",
    auth_prefix="Bearer",
    default_model="qwen3-max",
    supports_web_search=False,
    implemented=True,
    description="阿里云 DashScope 兼容接口下的通义千问对话模型",
    website="https://tongyi.aliyun.com/",
    docs_url="https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope",
)


QWEN_3_MAX = ModelConfig(
    id="qwen:qwen3-max",
    provider="qwen",
    name="qwen3-max",
    display_name="Qwen3 Max",
    supports_vision=False,
    supports_tools=True,
    supports_thinking=True,
    supports_web_search=False,
    supports_streaming=True,
    context_limit=262144,
    max_tokens_default=65536,
    max_tokens_thinking=32768,
    thinking_temperature=1.0,
    thinking_timeout=300,
    default_temperature=0.7,
    default_timeout=60,
    vision_fallback=None,
    is_vision_model=False,
    description="千问当前旗舰模型，支持 262K 上下文与思考模式，适合复杂多步骤任务",
)

QWEN_MAX = ModelConfig(
    id="qwen:qwen-max",
    provider="qwen",
    name="qwen-max",
    display_name="Qwen Max",
    supports_vision=False,
    supports_tools=True,
    supports_thinking=False,
    supports_web_search=False,
    supports_streaming=True,
    context_limit=32000,
    max_tokens_default=8192,
    max_tokens_thinking=8192,
    thinking_temperature=1.0,
    thinking_timeout=300,
    default_temperature=0.7,
    default_timeout=60,
    vision_fallback=None,
    is_vision_model=False,
    description="千问旗舰对话模型，适合通用复杂任务",
)

QWEN_PLUS = ModelConfig(
    id="qwen:qwen-plus",
    provider="qwen",
    name="qwen-plus",
    display_name="Qwen Plus",
    supports_vision=False,
    supports_tools=True,
    supports_thinking=True,
    supports_web_search=False,
    supports_streaming=True,
    context_limit=995904,
    max_tokens_default=32768,
    max_tokens_thinking=32768,
    thinking_temperature=1.0,
    thinking_timeout=300,
    default_temperature=0.7,
    default_timeout=60,
    vision_fallback=None,
    is_vision_model=False,
    description="千问增强模型，支持约 1M 上下文与思考模式，适合中等复杂任务",
)

QWEN_FLASH = ModelConfig(
    id="qwen:qwen-flash",
    provider="qwen",
    name="qwen-flash",
    display_name="Qwen Flash",
    supports_vision=False,
    supports_tools=True,
    supports_thinking=True,
    supports_web_search=False,
    supports_streaming=True,
    context_limit=995904,
    max_tokens_default=32768,
    max_tokens_thinking=32768,
    thinking_temperature=1.0,
    thinking_timeout=300,
    default_temperature=0.7,
    default_timeout=60,
    vision_fallback=None,
    is_vision_model=False,
    description="千问高吞吐低成本模型，支持约 1M 上下文与思考模式",
)

QWEN_TURBO = ModelConfig(
    id="qwen:qwen-turbo",
    provider="qwen",
    name="qwen-turbo",
    display_name="Qwen Turbo",
    supports_vision=False,
    supports_tools=True,
    supports_thinking=True,
    supports_web_search=False,
    supports_streaming=True,
    context_limit=131072,
    max_tokens_default=16384,
    max_tokens_thinking=16384,
    thinking_temperature=1.0,
    thinking_timeout=300,
    default_temperature=0.7,
    default_timeout=60,
    vision_fallback=None,
    is_vision_model=False,
    description="千问高吞吐模型，支持思考模式；当前预算按思考模式保守上限建模",
)

QWEN_LONG = ModelConfig(
    id="qwen:qwen-long",
    provider="qwen",
    name="qwen-long",
    display_name="Qwen Long",
    supports_vision=False,
    supports_tools=False,
    supports_thinking=False,
    supports_web_search=False,
    supports_streaming=True,
    context_limit=10000000,
    max_tokens_default=32768,
    max_tokens_thinking=32768,
    thinking_temperature=1.0,
    thinking_timeout=300,
    default_temperature=0.7,
    default_timeout=60,
    vision_fallback=None,
    is_vision_model=False,
    description="千问长上下文模型，适合超长文档分析、抽取与总结",
)


QWEN_MODELS = [
    QWEN_3_MAX,
    QWEN_MAX,
    QWEN_PLUS,
    QWEN_FLASH,
    QWEN_TURBO,
    QWEN_LONG,
]


__all__ = [
    "QWEN_PROVIDER",
    "QWEN_MODELS",
    "QWEN_3_MAX",
    "QWEN_MAX",
    "QWEN_PLUS",
    "QWEN_FLASH",
    "QWEN_TURBO",
    "QWEN_LONG",
]
