# Configuration Management
"""
配置管理模块

包含：
- settings.py: 默认设置常量
- credential_manager.py: 凭证管理器（敏感信息专用）
- config_manager.py: 配置统一访问管理器
"""

from .settings import (
    # 工作流默认值
    DEFAULT_MAX_CHECKPOINTS,
    DEFAULT_STAGNATION_THRESHOLD,
    DEFAULT_CONTEXT_LIMIT_RATIO,
    # LLM 默认值
    DEFAULT_TIMEOUT,
    DEFAULT_STREAMING,
    # RAG 默认值
    DEFAULT_CHUNK_SIZE,
    DEFAULT_CHUNK_OVERLAP,
    # 路径常量
    GLOBAL_CONFIG_DIR,
    GLOBAL_CONFIG_FILE,
    GLOBAL_LOG_DIR,
    WORK_FOLDER_HIDDEN_DIR,
    CREDENTIALS_FILE,
    # 国际化常量
    DEFAULT_LANGUAGE,
    SUPPORTED_LANGUAGES,
    # 配置字段名
    CONFIG_LANGUAGE,
    CONFIG_LLM_PROVIDER,
    CONFIG_API_KEY,
    CONFIG_TIMEOUT,
    CONFIG_STREAMING,
    CONFIG_EMBEDDING_PROVIDER,
    CONFIG_EMBEDDING_MODEL,
    # 凭证类型常量
    CREDENTIAL_TYPE_LLM,
    CREDENTIAL_TYPE_SEARCH,
    CREDENTIAL_TYPE_EMBEDDING,
    # 厂商常量
    LLM_PROVIDER_ZHIPU,
    LLM_PROVIDER_SILICONFLOW,
    LLM_PROVIDER_LOCAL,
    SUPPORTED_LLM_PROVIDERS,
    EMBEDDING_PROVIDER_LOCAL,
    EMBEDDING_PROVIDER_ZHIPU,
    SUPPORTED_EMBEDDING_PROVIDERS,
    # 默认配置模板
    DEFAULT_CONFIG,
)

from .credential_manager import CredentialManager
from .config_manager import ConfigManager

__all__ = [
    "CredentialManager",
    "ConfigManager",
    "DEFAULT_MAX_CHECKPOINTS",
    "DEFAULT_STAGNATION_THRESHOLD",
    "DEFAULT_CONTEXT_LIMIT_RATIO",
    "DEFAULT_TIMEOUT",
    "DEFAULT_STREAMING",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CHUNK_OVERLAP",
    "GLOBAL_CONFIG_DIR",
    "GLOBAL_CONFIG_FILE",
    "GLOBAL_LOG_DIR",
    "WORK_FOLDER_HIDDEN_DIR",
    "CREDENTIALS_FILE",
    "DEFAULT_LANGUAGE",
    "SUPPORTED_LANGUAGES",
    "CONFIG_LANGUAGE",
    "CONFIG_LLM_PROVIDER",
    "CONFIG_API_KEY",
    "CONFIG_TIMEOUT",
    "CONFIG_STREAMING",
    "CONFIG_EMBEDDING_PROVIDER",
    "CONFIG_EMBEDDING_MODEL",
    "CREDENTIAL_TYPE_LLM",
    "CREDENTIAL_TYPE_SEARCH",
    "CREDENTIAL_TYPE_EMBEDDING",
    "LLM_PROVIDER_ZHIPU",
    "LLM_PROVIDER_SILICONFLOW",
    "LLM_PROVIDER_LOCAL",
    "SUPPORTED_LLM_PROVIDERS",
    "EMBEDDING_PROVIDER_LOCAL",
    "EMBEDDING_PROVIDER_ZHIPU",
    "SUPPORTED_EMBEDDING_PROVIDERS",
    "DEFAULT_CONFIG",
]
